"""
DSPy modules and signatures for CV and JD extraction.

This package contains all DSPy signatures (input-output specifications) and
modules (extraction components) for structured data extraction from CVs and job descriptions.
"""

# CV Signatures
from .cv_signatures import (
    PersonalInfoExtraction,
    ProfessionalSummaryExtraction,
    WorkExperienceExtraction,
    WorkExperienceWithEvidence,
    EducationExtraction,
    EducationWithEvidence,
    TechnicalSkillsExtraction,
    SkillsWithProficiency,
    DomainSkillsExtraction,
    SkillWithEvidenceExtraction,
    CertificationExtraction,
    CertificationListExtraction,
    DivisionClassification,
    CareerProgressionAnalysis,
    JobHoppingDetection,
    RedFlagDetection,
    QualityScoring,
    KeyStrengthsExtraction,
    TotalExperienceCalculation,
    CVSectionDetection,
    StrictPersonalInfoExtraction,
    StrictSkillExtraction,
)

# JD Signatures
from .jd_signatures import (
    RoleInfoExtraction,
    LocationInfoExtraction,
    RequiredSkillsExtraction,
    SkillRequirementWithPriority,
    ComprehensiveSkillsExtraction,
    ExperienceRequirementsExtraction,
    EducationRequirementsExtraction,
    CertificationRequirementsExtraction,
    ResponsibilitiesExtraction,
    ResponsibilityPrioritization,
    CompensationExtraction,
    CompanyCultureExtraction,
    ApplicationInfoExtraction,
    JDDivisionClassification,
    RequirementsPriorityScoring,
    DisqualifiersExtraction,
    IdealCandidateProfile,
    JDQualityAssessment,
    MatchingWeightRecommendation,
    StrictRequirementExtraction,
    JDKeywordExtraction,
)

# CV Extraction Modules
from .cv_extraction_modules import (
    PersonalInfoExtractor,
    ProfessionalSummaryExtractor,
    WorkExperienceExtractor,
    BatchWorkExperienceExtractor,
    EducationExtractor,
    BatchEducationExtractor,
    TechnicalSkillsExtractor,
    SkillsWithProficiencyExtractor,
    DomainSkillsExtractor,
    SkillVerifier,
    BatchSkillVerifier,
    CertificationExtractor,
    CertificationListExtractor,
    DivisionClassifier,
    CareerProgressionAnalyzer,
    JobHoppingDetector,
    RedFlagDetector,
    QualityScorer,
    KeyStrengthsExtractor as CVKeyStrengthsExtractor,
    TotalExperienceCalculator,
    CVSectionDetector,
    ComprehensiveCVExtractor,
)

# JD Extraction Modules
from .jd_extraction_modules import (
    RoleInfoExtractor,
    LocationInfoExtractor,
    RequiredSkillsExtractor,
    ComprehensiveSkillsExtractor,
    SkillRequirementClassifier,
    BatchSkillRequirementClassifier,
    ExperienceRequirementsExtractor,
    EducationRequirementsExtractor,
    CertificationRequirementsExtractor,
    DisqualifiersExtractor,
    ResponsibilitiesExtractor,
    ResponsibilityPrioritizer,
    CompensationExtractor,
    CompanyCultureExtractor,
    ApplicationInfoExtractor,
    JDDivisionClassifier,
    RequirementsPriorityScorer,
    IdealCandidateProfileGenerator,
    JDQualityAssessor,
    MatchingWeightRecommender,
    JDKeywordExtractor,
    StrictRequirementExtractor,
    ComprehensiveJDExtractor,
    DivisionSpecificJDExtractor,
)


__all__ = [
    # CV Signatures
    "PersonalInfoExtraction",
    "ProfessionalSummaryExtraction",
    "WorkExperienceExtraction",
    "WorkExperienceWithEvidence",
    "EducationExtraction",
    "EducationWithEvidence",
    "TechnicalSkillsExtraction",
    "SkillsWithProficiency",
    "DomainSkillsExtraction",
    "SkillWithEvidenceExtraction",
    "CertificationExtraction",
    "CertificationListExtraction",
    "DivisionClassification",
    "CareerProgressionAnalysis",
    "JobHoppingDetection",
    "RedFlagDetection",
    "QualityScoring",
    "KeyStrengthsExtraction",
    "TotalExperienceCalculation",
    "CVSectionDetection",
    "StrictPersonalInfoExtraction",
    "StrictSkillExtraction",
    # JD Signatures
    "RoleInfoExtraction",
    "LocationInfoExtraction",
    "RequiredSkillsExtraction",
    "SkillRequirementWithPriority",
    "ComprehensiveSkillsExtraction",
    "ExperienceRequirementsExtraction",
    "EducationRequirementsExtraction",
    "CertificationRequirementsExtraction",
    "ResponsibilitiesExtraction",
    "ResponsibilityPrioritization",
    "CompensationExtraction",
    "CompanyCultureExtraction",
    "ApplicationInfoExtraction",
    "JDDivisionClassification",
    "RequirementsPriorityScoring",
    "DisqualifiersExtraction",
    "IdealCandidateProfile",
    "JDQualityAssessment",
    "MatchingWeightRecommendation",
    "StrictRequirementExtraction",
    "JDKeywordExtraction",
    # CV Modules
    "PersonalInfoExtractor",
    "ProfessionalSummaryExtractor",
    "WorkExperienceExtractor",
    "BatchWorkExperienceExtractor",
    "EducationExtractor",
    "BatchEducationExtractor",
    "TechnicalSkillsExtractor",
    "SkillsWithProficiencyExtractor",
    "DomainSkillsExtractor",
    "SkillVerifier",
    "BatchSkillVerifier",
    "CertificationExtractor",
    "CertificationListExtractor",
    "DivisionClassifier",
    "CareerProgressionAnalyzer",
    "JobHoppingDetector",
    "RedFlagDetector",
    "QualityScorer",
    "CVKeyStrengthsExtractor",
    "TotalExperienceCalculator",
    "CVSectionDetector",
    "ComprehensiveCVExtractor",
    # JD Modules
    "RoleInfoExtractor",
    "LocationInfoExtractor",
    "RequiredSkillsExtractor",
    "ComprehensiveSkillsExtractor",
    "SkillRequirementClassifier",
    "BatchSkillRequirementClassifier",
    "ExperienceRequirementsExtractor",
    "EducationRequirementsExtractor",
    "CertificationRequirementsExtractor",
    "DisqualifiersExtractor",
    "ResponsibilitiesExtractor",
    "ResponsibilityPrioritizer",
    "CompensationExtractor",
    "CompanyCultureExtractor",
    "ApplicationInfoExtractor",
    "JDDivisionClassifier",
    "RequirementsPriorityScorer",
    "IdealCandidateProfileGenerator",
    "JDQualityAssessor",
    "MatchingWeightRecommender",
    "JDKeywordExtractor",
    "StrictRequirementExtractor",
    "ComprehensiveJDExtractor",
    "DivisionSpecificJDExtractor",
]
